# TEMPLATE: Source Repository Trigger - Tag-Based Deployment
# Copy to: .github/workflows/trigger-docs-generation.yml (in your source repo)
#
# SETUP INSTRUCTIONS:
# 1. Replace {WORKFLOW_NAME} with your docs workflow name (env variable below)
#    Example: generate-api-docs-my-contract
# 2. Customize tag pattern if needed (lines 15 and 28)
#    Examples: 'v*', 'release-*', etc.
# 3. Add DOCS_REPO_TOKEN secret to your repository settings
# 4. Update docs repo name if not OpenZeppelin/docs (line 50)

name: Trigger API Documentation Generation

env:
  WORKFLOW_NAME: "{WORKFLOW_NAME}"  # TODO: Replace with your workflow filename (without .yml extension)

on:
  push:
    tags:
      - 'release-v*'  # TODO: Customize tag pattern if needed

jobs:
  trigger-docs-update:
    runs-on: ubuntu-latest

    steps:
      - name: Determine trigger type and ref
        id: trigger
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            # Tag-based trigger (e.g., release-v5.1.0)
            # TODO: Update pattern to match line 19
            if [[ "${{ github.ref_name }}" =~ ^release-v ]]; then
              echo "ref_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
              echo "trigger_type=tag" >> $GITHUB_OUTPUT
              echo "📋 Trigger type: Tag"
              echo "🏷️  Tag: ${{ github.ref_name }}"
            else
              echo "⚠️  Tag does not match release-v* pattern, skipping"
              exit 0
            fi
          else
            echo "⚠️  Not a tag push, skipping"
            exit 0
          fi

      - name: Trigger documentation generation
        if: steps.trigger.outputs.ref_name != ''
        env:
          GH_TOKEN: ${{ secrets.DOCS_REPO_TOKEN }}
        run: |
          gh workflow run ${{ env.WORKFLOW_NAME }}.yml \
            --repo OpenZeppelin/docs \
            --field tag_name="${{ steps.trigger.outputs.ref_name }}" \
            --field trigger_type="${{ steps.trigger.outputs.trigger_type }}"

          echo "✅ Triggered documentation generation for ${{ steps.trigger.outputs.ref_name }}"
          echo "📍 Repository: ${{ github.repository }}"
          echo "🔖 Reference: ${{ steps.trigger.outputs.ref_name }}"
          echo "📋 Type: ${{ steps.trigger.outputs.trigger_type }}"
